version: '3.9'
    
services:

  # front container
  front-app:
    container_name: mcda-front
    image: mcda-front:latest
    env_file:
      - .env
    ports:
      - $FRONT_LOCAL_PORT:$FRONT_DOCKER_PORT
   
  # database
  mysqldb:
    container_name: mcda-db
    image: mcda-db:latest
    env_file:
      - .env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    
    
   # api container
  springboot-app:
    restart: always
    container_name: mcda-api-deploy
    image: mcda-api-deploy:latest
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.show-sql" : "true",
        "spring.jpa.properties.hibernate.format_sql" : "true",
        "spring.jpa.hibernate.ddl-auto" : "update", 
        "logging.file.path" : "logs"
      }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2 
    depends_on:
      - mysqldb

  
  
  

  

  
  
        
